# Generated by Django 5.0 on 2024-01-07 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerdocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/docs'),
        ),
        migrations.AlterField(
            model_name='lawyerdocument',
            name='pdf_file',
            field=models.FileField(upload_to='core/images', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
