# Generated by Django 5.0 on 2024-01-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lawyerdocument_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='lawyerprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
