# Generated by Django 5.0 on 2024-01-07 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerdocument',
            name='image',
        ),
        migrations.AlterField(
            model_name='lawyerdocument',
            name='pdf_file',
            field=models.FileField(upload_to='core/docs', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.CreateModel(
            name='LawyerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='core/images')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.lawyerprofile')),
            ],
        ),
    ]
