# Generated by Django 5.0 on 2024-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
