# Generated by Django 5.0 on 2024-01-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lawyerprofile_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='availability',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
    ]
