# Generated by Django 5.0 on 2024-01-24 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lawyerprofile'),
        ),
    ]
