# Generated by Django 5.0 on 2024-01-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_timeslot_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.lawyerprofile'),
        ),
    ]
