# Generated by Django 5.0 on 2024-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_lawyerprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerimage",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="core/images"
            ),
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="bio",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="specialization",
            field=models.CharField(max_length=1500),
        ),
    ]
