# Generated by Django 5.0 on 2024-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_lawyerimage_image_alter_lawyerprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerprofile",
            name="bio",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="specialization",
            field=models.CharField(max_length=2000),
        ),
    ]
