# Generated by Django 5.0 on 2024-01-28 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_lawyerprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="core.lawyerprofile",
            ),
        ),
    ]
