# Generated by Django 5.0 on 2024-01-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_appointment_note_appointment_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.CharField(max_length=255),
        ),
    ]
