CREATE TABLE "auth_permission" (
  "id" int NOT NULL AUTO_INCREMENT,
  "name" varchar(255) NOT NULL,
  "content_type_id" int NOT NULL,
  "codename" varchar(100) NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE KEY "auth_permission_content_type_id_codename_01ab375a_uniq" ("content_type_id","codename"),
  CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id")
);insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_logentry', 1, 1, 'Can add log entry');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_logentry', 1, 2, 'Can change log entry');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_logentry', 1, 3, 'Can delete log entry');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_logentry', 1, 4, 'Can view log entry');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_permission', 2, 5, 'Can add permission');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_permission', 2, 6, 'Can change permission');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_permission', 2, 7, 'Can delete permission');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_permission', 2, 8, 'Can view permission');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_group', 3, 9, 'Can add group');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_group', 3, 10, 'Can change group');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_group', 3, 11, 'Can delete group');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_group', 3, 12, 'Can view group');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_user', 4, 13, 'Can add user');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_user', 4, 14, 'Can change user');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_user', 4, 15, 'Can delete user');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_user', 4, 16, 'Can view user');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_contenttype', 5, 17, 'Can add content type');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_contenttype', 5, 18, 'Can change content type');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_contenttype', 5, 19, 'Can delete content type');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_contenttype', 5, 20, 'Can view content type');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_session', 6, 21, 'Can add session');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_session', 6, 22, 'Can change session');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_session', 6, 23, 'Can delete session');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_session', 6, 24, 'Can view session');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_site', 7, 25, 'Can add site');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_site', 7, 26, 'Can change site');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_site', 7, 27, 'Can delete site');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_site', 7, 28, 'Can view site');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_emailaddress', 8, 29, 'Can add email address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_emailaddress', 8, 30, 'Can change email address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_emailaddress', 8, 31, 'Can delete email address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_emailaddress', 8, 32, 'Can view email address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_emailconfirmation', 9, 33, 'Can add email confirmation');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_emailconfirmation', 9, 34, 'Can change email confirmation');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_emailconfirmation', 9, 35, 'Can delete email confirmation');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_emailconfirmation', 9, 36, 'Can view email confirmation');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_socialaccount', 10, 37, 'Can add social account');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_socialaccount', 10, 38, 'Can change social account');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_socialaccount', 10, 39, 'Can delete social account');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_socialaccount', 10, 40, 'Can view social account');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_socialapp', 11, 41, 'Can add social application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_socialapp', 11, 42, 'Can change social application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_socialapp', 11, 43, 'Can delete social application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_socialapp', 11, 44, 'Can view social application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_socialtoken', 12, 45, 'Can add social application token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_socialtoken', 12, 46, 'Can change social application token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_socialtoken', 12, 47, 'Can delete social application token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_socialtoken', 12, 48, 'Can view social application token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_address', 13, 49, 'Can add address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_address', 13, 50, 'Can change address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_address', 13, 51, 'Can delete address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_address', 13, 52, 'Can view address');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_administrator', 14, 53, 'Can add administrator');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_administrator', 14, 54, 'Can change administrator');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_administrator', 14, 55, 'Can delete administrator');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_administrator', 14, 56, 'Can view administrator');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_clientprofile', 15, 57, 'Can add client profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_clientprofile', 15, 58, 'Can change client profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_clientprofile', 15, 59, 'Can delete client profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_clientprofile', 15, 60, 'Can view client profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_lawyerprofile', 16, 61, 'Can add lawyer profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_lawyerprofile', 16, 62, 'Can change lawyer profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_lawyerprofile', 16, 63, 'Can delete lawyer profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_lawyerprofile', 16, 64, 'Can view lawyer profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_lawyerdocument', 17, 65, 'Can add lawyer document');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_lawyerdocument', 17, 66, 'Can change lawyer document');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_lawyerdocument', 17, 67, 'Can delete lawyer document');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_lawyerdocument', 17, 68, 'Can view lawyer document');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_review', 18, 69, 'Can add review');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_review', 18, 70, 'Can change review');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_review', 18, 71, 'Can delete review');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_review', 18, 72, 'Can view review');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_timeslot', 19, 73, 'Can add time slot');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_timeslot', 19, 74, 'Can change time slot');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_timeslot', 19, 75, 'Can delete time slot');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_timeslot', 19, 76, 'Can view time slot');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_appointment', 20, 77, 'Can add appointment');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_appointment', 20, 78, 'Can change appointment');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_appointment', 20, 79, 'Can delete appointment');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_appointment', 20, 80, 'Can view appointment');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_lawyerimage', 21, 81, 'Can add lawyer image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_lawyerimage', 21, 82, 'Can change lawyer image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_lawyerimage', 21, 83, 'Can delete lawyer image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_lawyerimage', 21, 84, 'Can view lawyer image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_application', 22, 85, 'Can add application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_application', 22, 86, 'Can change application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_application', 22, 87, 'Can delete application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_application', 22, 88, 'Can view application');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_accesstoken', 23, 89, 'Can add access token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_accesstoken', 23, 90, 'Can change access token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_accesstoken', 23, 91, 'Can delete access token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_accesstoken', 23, 92, 'Can view access token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_grant', 24, 93, 'Can add grant');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_grant', 24, 94, 'Can change grant');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_grant', 24, 95, 'Can delete grant');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_grant', 24, 96, 'Can view grant');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_refreshtoken', 25, 97, 'Can add refresh token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_refreshtoken', 25, 98, 'Can change refresh token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_refreshtoken', 25, 99, 'Can delete refresh token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_refreshtoken', 25, 100, 'Can view refresh token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_idtoken', 26, 101, 'Can add id token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_idtoken', 26, 102, 'Can change id token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_idtoken', 26, 103, 'Can delete id token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_idtoken', 26, 104, 'Can view id token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_association', 27, 105, 'Can add association');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_association', 27, 106, 'Can change association');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_association', 27, 107, 'Can delete association');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_association', 27, 108, 'Can view association');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_code', 28, 109, 'Can add code');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_code', 28, 110, 'Can change code');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_code', 28, 111, 'Can delete code');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_code', 28, 112, 'Can view code');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_nonce', 29, 113, 'Can add nonce');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_nonce', 29, 114, 'Can change nonce');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_nonce', 29, 115, 'Can delete nonce');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_nonce', 29, 116, 'Can view nonce');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_usersocialauth', 30, 117, 'Can add user social auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_usersocialauth', 30, 118, 'Can change user social auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_usersocialauth', 30, 119, 'Can delete user social auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_usersocialauth', 30, 120, 'Can view user social auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_partial', 31, 121, 'Can add partial');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_partial', 31, 122, 'Can change partial');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_partial', 31, 123, 'Can delete partial');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_partial', 31, 124, 'Can view partial');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_multifactorauth', 32, 125, 'Can add multi factor auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_multifactorauth', 32, 126, 'Can change multi factor auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_multifactorauth', 32, 127, 'Can delete multi factor auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_multifactorauth', 32, 128, 'Can view multi factor auth');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_token', 33, 129, 'Can add Token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_token', 33, 130, 'Can change Token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_token', 33, 131, 'Can delete Token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_token', 33, 132, 'Can view Token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_tokenproxy', 34, 133, 'Can add token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_tokenproxy', 34, 134, 'Can change token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_tokenproxy', 34, 135, 'Can delete token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_tokenproxy', 34, 136, 'Can view token');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_userprofile', 35, 137, 'Can add user profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_userprofile', 35, 138, 'Can change user profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_userprofile', 35, 139, 'Can delete user profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_userprofile', 35, 140, 'Can view user profile');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('add_clientimage', 36, 141, 'Can add client image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('change_clientimage', 36, 142, 'Can change client image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('delete_clientimage', 36, 143, 'Can delete client image');
insert into `auth_permission` (`codename`, `content_type_id`, `id`, `name`) values ('view_clientimage', 36, 144, 'Can view client image');
