CREATE TABLE "core_address" (
  "id" bigint NOT NULL AUTO_INCREMENT,
  "street" varchar(255) DEFAULT NULL,
  "city" varchar(255) DEFAULT NULL,
  "state" varchar(255) DEFAULT NULL,
  "zip_code" varchar(255) DEFAULT NULL,
  "country" varchar(255) DEFAULT NULL,
  "latitude" decimal(10,6) DEFAULT NULL,
  "longitude" decimal(10,6) DEFAULT NULL,
  PRIMARY KEY ("id")
);insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('alger centre', 'dz', '1', NULL, NULL, 'alger', 'qwerty', '16000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Anytown', '', '2', NULL, NULL, 'CA', '123 Main St', '12345');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Anytown', '', '3', NULL, NULL, 'CA', '123 Main St', '12345');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Anytown', '', '4', NULL, NULL, 'CA', '123 Main St', '12345');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Anytown', '', '5', NULL, NULL, 'CA', '123 Main St', '12345');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Anytown', '', '6', NULL, NULL, 'CA', '123 Main St', '12345');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'dz', '7', NULL, NULL, 'alger', 'Alger', '32423432');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Anytown', 'USA', '8', NULL, NULL, 'NY', '123 Main St', '12345');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('alger', 'dz', '9', NULL, NULL, 'alger', '12 sdfdsf', '32423432');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Amizour', 'dz', '10', NULL, NULL, 'Bougie', 'No where', '2342421');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('adsfsadf', 'dz', '11', NULL, NULL, 'sadfdsafsf', 'adsfadsf', '2343242');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('alger', 'dz', '12', NULL, NULL, 'alger', '23 weffaff', '23423423');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Batna', 'N⁰ 30', '100', NULL, NULL, 'Rue des Frères BOUABSA', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'W49A', '101', NULL, NULL, 'Rue Kaloua el cheref Hassi Mameche', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algerie', '1 rue ezzroug ezzraimi', '102', NULL, NULL, '( place ettoute) Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Hassi Bahbah 17000', '103', NULL, NULL, 'Djelfa', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Messaâd', '104', NULL, NULL, 'Djelfa', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '105', NULL, NULL, 'Skikda', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Coop cilfa ben mred Bordj el kiffan', '106', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('a côté du tribunal de Ouargla', '', '107', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('N°6 Rue 8  Tissemsilt', '', '108', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algèrie', 'rue Chenoua Hydra', '109', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('23 Rue Ben Amiour Abdelkader Annaba', '', '110', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algèrie', '', '111', NULL, NULL, 'Mascara .Mohammadia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Mohamed V', '112', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('N°03 Rue Ben boulaid el hadjar Annaba', '', '113', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '114', NULL, NULL, 'Citè 410 lgts  Batna', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('GHAZAOUET', '', '115', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'tolga', '116', NULL, NULL, 'Biskra', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue11 Décembre 1960', '117', NULL, NULL, 'Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '118', NULL, NULL, '11 rue bouzbide Ahmed Annaba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algerie', '', '119', NULL, NULL, 'Cité 400 Logst Bâtiment B 8 N 44 en face lycee Chihab El eulma wilaya de sétif', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algerie.', '', '120', NULL, NULL, 'zone sud Quartier A N°8 tizi ouzou', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Belaouni Benaissa', '121', NULL, NULL, 'Mascara', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '25 rue emir abdelkader', '122', NULL, NULL, 'Annaba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité brahmia sadek 172 logements bloc A7 N° 01 Tebessa', '', '123', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '124', NULL, NULL, 'Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité cnep chevalley Bouzareah', '', '125', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Hadj Abdelmadjid Abbdessamed', '126', NULL, NULL, 'Batna', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algèrie', 'Cité Malki bt j 7 n 3 Ben Aknoun', '127', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '128', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Kouba', '129', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Zabana', '130', NULL, NULL, 'Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Tebesbest', '131', NULL, NULL, 'Touggourt', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('11 RUE TALEB ABDERHAMENE BEB EL OUED ALGER', '', '132', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '133', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Café de Diden', '134', NULL, NULL, 'Ain Temouchent', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('36 rue boukhezer ahmed (ex rue Montaigne) Bab El Oued Alger', '', '135', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'N48', '136', NULL, NULL, 'El Oued', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '137', NULL, NULL, 'Cité Djawwed Eldjadid BISKRA', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('medea', '', '138', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('20 rue fréres Faress ( ibn badiss) Tiaret', '', '139', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Italie', '', '140', NULL, NULL, 'Montecompatri RM', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Larbi Abdelsalem', '141', NULL, NULL, 'Rouïba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Oran', '', '142', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('ALGERIE', 'Cité  Lahlou', '143', NULL, NULL, 'BOUIRA', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '27 Rue Larbi Ben M\'hidi', '144', NULL, NULL, 'Alger Ctre', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '145', NULL, NULL, 'El Khroub', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cite lescure bt e5 n 2 oran', '', '146', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité de la Paix. bloc administrative premier étage. en face de la BADR banque. Tébessa  Algerie', '', '147', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algerie', '06 rue du moulin', '148', NULL, NULL, 'Relizane', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('04 Rue Khelifa Boukhalefa Alger centre 16000', '', '149', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '150', NULL, NULL, 'Ghazaouet Tlemcen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('bordj boureridj', 'media', '151', NULL, NULL, 'mesila', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('khenchela Boulevard ben boulaid', '', '152', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bechar', '', '153', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('boulevard Comandant Djaoudi Abderrahmane - Hai el Amir 31010 - Oran. (ex bd charlemagne - hotel de ville)', '', '154', NULL, NULL, '6', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Boulevard Victor Hugo', '155', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité GARIDI 1 BT 46 N 05 KOUBA ALGER', '', '156', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '157', NULL, NULL, 'Bordj El kiffan', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '17 AVENUE MOHAMED', '158', NULL, NULL, 'Belouizdad', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '35 RUE BOUAMAMA', '159', NULL, NULL, 'El Harrach', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Hussein-Dey - ALGER', '', '160', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '1100', '161', NULL, NULL, 'Bouira', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Mostaganem 27000', '', '162', NULL, NULL, 'Bloc 135 Étage 3(A)، Cité 5 Juillet', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'CEM Guizi Said', '163', NULL, NULL, 'Bouira', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Darrar abderrahmen  TLEMCEN', '', '164', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue ATTIA AHMED N=01 - Annaba -23000', '', '165', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('.', 'Cité lescure batiment 6', '166', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Tobbal Béjaia', '', '167', NULL, NULL, 'Cité 96 Logements Bt A04 N30', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Hydra Alger', '2 Chemin Beauregard', '168', NULL, NULL, 'El Mouradia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16002 Alger', 'Dar Diaf', '169', NULL, NULL, 'Chéraga', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Said Hamdine Alger', '', '170', NULL, NULL, '348 logts Immeuble 5 numéro 3', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '171', NULL, NULL, '31 Boulevard Zighoud Youcef', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '2 Rue Ali Boumendjel', '172', NULL, NULL, 'Alger Centre', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('15 Rue Larbi Ben M\'hidi Alger', '', '173', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Kouba Alger', 'Villa 32', '174', NULL, NULL, 'Rue des Fréres Khennouche', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16000 Alger', '', '175', NULL, NULL, '5 Rue Omar Amimour (ex. Elysée Reclus )', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('27000 Mostaganem', 'Cité 400 logements', '176', NULL, NULL, 'Route d\'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16004 ALGER', '117', '177', NULL, NULL, 'rue Didouche Mourad', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'rue Letellier', '178', NULL, NULL, 'Sacré Cœur', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('B.P.16000 Alger', '', '179', NULL, NULL, '6 Rue Larbi Ben M\'Hidi', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Benaknoun Alger', '', '180', NULL, NULL, '18 Chemin Khalef Mustapha', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('46 Rue Rabah Bourbia (Ex chemin luciani) El Biar Alger', '', '181', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16004 Alger', '20 rue Claude Debussy', '182', NULL, NULL, 'Alger Centre', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '23 clos des vergers', '183', NULL, NULL, 'Kouba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16000 Alger', '', '184', NULL, NULL, '39 rue Louis Rougé. El biar', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('31000 Oran', '', '185', NULL, NULL, '23 Rue HAOUES La Houari', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'les Sources', '186', NULL, NULL, 'Birmandreis', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16000 Alger', '4', '187', NULL, NULL, 'rue Abane Ramdane', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('15000 Tizi-Ouzou', '', '188', NULL, NULL, '9 rue des frères Sidi-Mâamar', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité des 348 Logts Bt 05 N° 03 Said Hamdine 16013 Alger', '', '189', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16000 Alger', '', '190', NULL, NULL, '10 rue Enfantin', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('wilaya de Blida', '04 rue Abdellah abdelkader 09200', '191', NULL, NULL, 'El affroun', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger centre 16000', '', '192', NULL, NULL, 'Rue Rachid Tidjani', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger centre', '', '193', NULL, NULL, '43 Rue Didouche Mourad', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Reghaia Alger', 'Cité Bouzegza', '194', NULL, NULL, 'Bâtiment 1 n°44', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'Citée des Annassers', '195', NULL, NULL, '2 bt C4 Kouba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '9ème Groupe', '196', NULL, NULL, 'Bloc(C)', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Kouba 16308 Alger', '', '197', NULL, NULL, 'Lawhouse - Annassers II Bt A 28 n°2', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger Centre', '2 Rue Omar Bencheickh', '198', NULL, NULL, 'Bd Larbi Ben M\'hidi', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '78 Lot Oued Torfa', '199', NULL, NULL, 'Draria', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('26 boulevard Zirout Youcef Alger /', '', '200', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('16000 Alger', '', '201', NULL, NULL, '78 rue Didouche Mourad', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bordj Bou Arreridj', '', '202', NULL, NULL, 'Cité des 1008/738 bloc 21 n°164', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('rue Voltaire Alger', '', '203', NULL, NULL, '4', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '204', NULL, NULL, '2 rue des frères Ferroum BP 327 Kouba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Pins Maritimes - 16130 Alger Mohammadia', '', '205', NULL, NULL, 'Tour  Business Center', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('30000 Ouargla', '', '206', NULL, NULL, 'Hassi-Messaoud', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Hydra', '207', NULL, NULL, '16035 Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Hydra', '208', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Ben Aknoun', '209', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Elmoudjahidin N:43Ben Aknoun .Alger  Alger 16000', '', '210', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '31000', '211', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '49 rue zaghloul Es Senia', '212', NULL, NULL, 'Oran 31000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('.', '31000', '213', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '31000', '214', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Oran', '', '215', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('.', '31000', '216', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('.', '31000', '217', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('.', '31000', '218', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('14 QUAI KLEBER. Strasbourg', '', '219', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bejaia', '', '220', NULL, NULL, 'Rue des 7 Martyrs  06011 Seddouk Centre', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('74 rue Blanche - 75009 Paris', '', '221', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Cité Haouet Ameur', '222', NULL, NULL, 'Tlemcen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Boufarik', '223', NULL, NULL, 'Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('BLIDA', '', '224', NULL, NULL, '04 PLACE DES MARTYRES', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Hussein-Dey - ALGER', 'Cité Patrimoine villaC9', '225', NULL, NULL, 'El Magharia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'DELLYS', '226', NULL, NULL, 'Boumerdès', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('21 rue CNRA 23000 ANNABA ALGÉRIE', '', '227', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Mohamed El-Mouheb', '228', NULL, NULL, 'Tigzirt 15019', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '26', '229', NULL, NULL, 'boulevard Zirout  Youcef', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('11 rue el quods constantine algérie', '', '230', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('3 Clos Les Vergers Kouba Alger', '', '231', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '232', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '233', NULL, NULL, 'Koléa', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '234', NULL, NULL, '73 Lots N° 35 Ain Bey Les 4 Chemin Constantine', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '235', NULL, NULL, 'Ancienne caserne premier etage B n 01 Guelma', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Ali Abdenour', '236', NULL, NULL, 'Skikda', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'barreau de Blida', '237', NULL, NULL, '41 rue Mohamed fidai Chlef', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'barreau d\'Alger', '238', NULL, NULL, 'Rue Djebel Bouzegza El Harrach', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'n 62 beni abbes', '239', NULL, NULL, 'Bechar', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('ALGER', '', '240', NULL, NULL, 'Lot Appreval RW50 Immeuble Fadli   Bt B N°6  16009  KOUBA', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Hussein-Dey', '241', NULL, NULL, 'ALGER', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'barreau de sétif', '242', NULL, NULL, '14 rue el fida sétif', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue N°03 Aissat idir cheraga', '243', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cab : 11 Rue Larachiche Med Khemis Miliana', '', '244', NULL, NULL, 'barreau de Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cité Elchahid Djouab Chemin Doudou Mokhtar Ben Aknoun– Alger –', '', '245', NULL, NULL, '02 B', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('169 Rue de l\'A.LN. Hamma Bouziane Constantine', '', '246', NULL, NULL, 'barreau de Constantine', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '14 rue el fida', '247', NULL, NULL, 'setif', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger.', '5 Rue Lieutenant Ahmed Garani', '248', NULL, NULL, 'Casbah', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '249', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('76 Rue Réaumur Paris 75002', '', '250', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('ALGERIE', '', '251', NULL, NULL, 'Cité BOUTRIK Embarek Sour El Ghozlane 10004 Wilaya de BOUIRA', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Centre ville', '252', NULL, NULL, 'Tamanrasset', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Carrefour Dr Merghoub Centre ville Ghardaïa Algerie', '', '253', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Khenchela', '254', NULL, NULL, 'Khenchela (40)', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Ben Aknoun', '255', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'Côte Blanche', '256', NULL, NULL, 'Souidania', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('107 lot karra slimane kiffane Tlemcen', '', '257', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Mostaganem', '', '258', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Ben Aknoun Alger', '', '259', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Castellón (Espagne)', '', '260', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('28 avenue Claude Debussy Alger', '', '261', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bouira.', '39', '262', NULL, NULL, 'Rue Gharbi Guemraoui', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Oran', '', '263', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '01 Rue Abderrahmane Hami', '264', NULL, NULL, 'Bab El Oued 16000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Birkhadem Alger', '', '265', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '266', NULL, NULL, 'Skikda', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('2', '', '267', NULL, NULL, 'promotion gare routière bt n°:02', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '268', NULL, NULL, 'Rue Kelkacem Ouzri n 15 Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger villa n 18 El Mouradia Alger', '', '269', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('19 Rue Chihani Bachir . Souk Ahras', '', '270', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('220 RUE MED BELOUIZDAD RUISSEAU ALGER', '', '271', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Sidi M\'hamed Alger', '', '272', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algerie', '09 Boulakroun Mohamed St Jean', '273', NULL, NULL, 'Constantine', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('18 Rue Ahmed Zabanna Alger', '', '274', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Kouba', '275', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '276', NULL, NULL, 'Aïn Fakroun', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cite 05 juillet Bt D91 N° 05 Bab ezzouar Alger', '', '277', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Avnue 1 novembre boudouaou boumerdes', '', '278', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('65 Rue de Tripoli Hussein Day Alger', '', '279', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'rue Khelifa Boukhalfa (ex-rue Richelieu) - Alger Centre', '280', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Mostaganem', '', '281', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Saâda ex-protin bloc S n\'02 Oran', '', '282', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('n 27 00000 31 - Oran', '', '283', NULL, NULL, 'Larbi Ben M\'hidi', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('dd', 'cgvhjk', '284', NULL, NULL, 'aaaz', 'gd', '15000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('tizi ouzou', 'vgghhn', '285', NULL, NULL, 'aaaz', 'aa', '44');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('06 rue 5 juillet El harrach Alger - Alger', '', '286', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Derrar Abderrahmen Kifan', '', '287', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Constantine', '', '288', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Hassi Ben Abdellah - Ouargla', '', '289', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Hassi Messaoud', '290', NULL, NULL, 'Ouargla (30)', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Ouargla & hassi Messaoud', '', '291', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue REMMACH Aissa 3400 Bordj Bou Arréridj', '', '292', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Said Hamdine', '293', NULL, NULL, 'Bir Mourad Raïs', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('TIZI OUZOU', '', '294', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '295', NULL, NULL, 'Dar El Beïda', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('11 Rue Henri Dunant Alger', '', '296', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Vers Bou-ismail', '297', NULL, NULL, 'Fouka', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('39 auto construction draria alger.', '', '298', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Tiaret 14000', '', '299', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Annaba', '23', '300', NULL, NULL, 'Bennamiour Abdelkader', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Lotissement Douzi 01 N°26 Bab Ezzouar Alger', '', '301', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Centre Ville Oran', '', '302', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Hai Bouamama Ilot 574 n°380 ORAN', '', '303', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Bahmid Bloc C n°2 Ouargla', '', '305', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Blida', '', '306', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('HAY NASR ZONE 5A CHLEF', '', '307', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité HLM 2 ème groupe bt B hamma el annasser', '', '308', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('143 rue Larbi Ben M\'hidi Didouche Mourad Constantine', '', '309', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('rue du Cardinal Mercier  75009 PARIS', '', '310', NULL, NULL, '8', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue du Criblet 5  1700 Fribourg', '', '312', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '313', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '314', NULL, NULL, 'Rue du Parc Hydra', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('21 -A Said Hamdine Bir Morad Rais Alger', '', '315', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '316', NULL, NULL, 'Wilaya de Aïn Defla', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('France', '', '317', NULL, NULL, '79 rue de la santé (617.98 km) 75013 Paris', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('elmanzah1 1 tunis', '', '318', NULL, NULL, '14 rue Esseyouti.', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cooperative el fath soumaa blida', '', '319', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('BEJAIA 06310 - El Kseur Algerie', 'Route De TIZI OUZOU', '321', NULL, NULL, 'EL Kseur', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '750 Boulevard Laribi Lakhder', '322', NULL, NULL, 'Bordj Bou Arreridj 34000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 572/2226 Logts Bt 79 C n°01 Ain Naadja -Gue de Constantine -Alger', '', '323', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Chemin des Crêtes – Le Paradou – Alger', '', '324', NULL, NULL, '8', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('02 rue Abane Ramdane Alger', '', '325', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Mostaganem algerie', '', '326', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('06 Angle rue Toulouse et rue Tripoli', '', '327', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '328', NULL, NULL, 'Bir Mourad Raïs', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Asla Hocine', '329', NULL, NULL, 'Annaba', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Des Fonctionnaires Bloc:C1C : CHLEF', '', '330', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('8 rue hamlaoui Constantine', '', '331', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('02 rue saad taleb alger centre', '', '332', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('RUE SAID AYAD', '', '333', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'El-Biar', '334', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('MH.L.M', '', '335', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'Avenue El Ahrar', '336', NULL, NULL, 'El Mouradia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '337', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('place Tarik Ib Ziad 23000 - Annaba', '', '338', NULL, NULL, '8', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Lamara Abdelkader - ANNABA', '', '339', NULL, NULL, '4', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'Texraine', '340', NULL, NULL, 'Bir Khadem', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Tizi Ouzzou Ville', '', '341', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 594 logt bt D5 N 3 aadl bach djerah', '', '343', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('36 rue des freres abedeli hai an nasr Batna 05000', '', '344', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('41 rue Ali Medouche ex Vauban Hussein Dey Alger', '', '345', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cite de la paix Tebessa', '', '346', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '347', NULL, NULL, '22 rue Askri Hcen Bab El Oued', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('N 11 chemin des jeunes aveugles draria alger', '', '348', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger 16000', 'Said Hadmine', '349', NULL, NULL, 'Bir Mourad Rais', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Chéraga Alger', '', '350', NULL, NULL, '07 Rue Tella Ahcena', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '351', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '352', NULL, NULL, 'Alger Centre', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('46 rue Rabah bourbia ex chemin luciani El Biar', '', '353', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('N 11 chemin des jeunes aveugles draria alger', '', '354', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cheraga Alger', '', '355', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('ksar el fougani Tamenrasset', '', '356', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Grand Chéraga Chéraga 16000 – Alger', '', '357', NULL, NULL, '54 Sidi Hassen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('31cité Djebli Mohamed. 27000 Mostaganem', '', '358', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité El Moudjahidin numéro 43 Chevaly - Alger 16000 Alger', '', '359', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '360', NULL, NULL, '202 Bis Rue Mohamed Belouizdad Ruisseau', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Boulevard Sidi Abed n°06 48000 Relizane', '', '361', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('02 Rue Frères Tahar et Mouloud Alak Sidi Mhamed Alger 16000 Alger', '', '362', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité diar eljamaa bloc 3 cage f 117 Bach jarah alger 16000 Alger', '', '363', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue frères SAHRAOUI Boudouaou 35400 Boumerdes', '', '364', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Algerie', 'Lotissement Kara Slimane n10', '365', NULL, NULL, 'Tlemcen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 100 logts Aissat Idir Enface Tribunal de Chéraga Alger', '', '366', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('11 - Ain Djenna - Mazouna -RELIZANE - ALGERIE -48220.', '', '367', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'N5', '368', NULL, NULL, 'Bouira', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('43 rue 11 décembre 1960 el biar Alger (résidence fadli salah)', '', '369', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('13 Rue Moussa Rebai Beb El Oued Alger Centre', '', '370', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Batna', '', '371', NULL, NULL, 'Arris', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger Cheraga', '', '372', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Bâtiment 27', '373', NULL, NULL, 'Cité 1406 Logts، Boumerdes 35000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité El Moudjahidin numéro 43 Chevaly - Alger', '', '375', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cabinet d\'avocat mr ayachi', '', '376', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Gascogne Alger Alger Centre 16001', '', '377', NULL, NULL, '10', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '19 Boulevard Hamou', '378', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('05 rue des lois Oran', '', '379', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'N25', '380', NULL, NULL, 'Dar El Beïda', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('36 rue Mberbache Abdelkader Mediouni Oran', '', '381', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Coopérative Cheraitia. Haï Gaaloul. Alger Plage', '', '382', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '383', NULL, NULL, 'Said Hamdine', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Palestine Ste Coopérative PIMA Bt B N 03 - Blida', '', '384', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rouiba', '', '385', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('26 Hihi Mekki Oum el Bouaghi', '', '386', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('11 Rue Khaled Abdelkader', '', '387', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('11 Rue Khaled Abdelkader Tlemcen', '', '388', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '389', NULL, NULL, '14 Rue Badr Kouba Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Casba. Place des Martyrs Alger', '', '390', NULL, NULL, '8 avenue du 1er novembre 1954', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '18 avenue du 1er Novembre', '391', NULL, NULL, '16009', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Souk Ahras', '2 Rue Ahcen Belaboudi', '392', NULL, NULL, '41000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 400 logements bâtiment 12 numéro 20 les eucalyptus Alger', '', '393', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('3 Place Port Saïd Alger', '', '394', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('log OPGI Draria.  Alger 16000', '', '395', NULL, NULL, '42', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger Centre', '', '396', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger 16000', '72 Bis Bois des cars 2', '397', NULL, NULL, 'Dely Brahim', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('rue Capitaine Mennani 16000 Alger.', '', '398', NULL, NULL, '31', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('348 Logts Bt N03 Said Hamdine (Hydra) - Alger 16013', '', '399', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Coopérative immobilière en-asr n 11 Reghaia  Alger', '', '400', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger.', 'rue Tolstoï (Lots Piete)', '401', NULL, NULL, 'BP 435 Hydra 16035', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('rue colonelle bouguerra 42400.w de Tipaza.', '', '402', NULL, NULL, '16', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '403', NULL, NULL, 'Residence des 24 logements  Said Hamdine', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Belle Vue Stand Batna', '', '404', NULL, NULL, '6', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Coopérative immobilière djurdjura souk el khemis Maatkas Tizi ouzou', '', '405', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Rue Handel Ahmed', '406', NULL, NULL, 'Souk-Ahras', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '5 Rue Med khider', '407', NULL, NULL, 'BenAknoun', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('08 rue Bourtima Mohamed. Djidiouia. Relizane.', '', '408', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('400 log el Oued', '', '409', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Akbou Béjaïa', '', '410', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger Centre', '', '411', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('18 rue chick Belhaddad bordj bou arreridj', '', '412', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cite martyre bouteldja boudjamaa grarem gouga wilaya de mila', '', '413', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Secteur D 2 rue dz N°278 B.B.Arreridj', '', '414', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'N41', '417', NULL, NULL, 'Ben Aknoun', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Batna', '', '418', NULL, NULL, 'Cité an Nasr', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('04 boulevard EMIR ABDELKADER. Oran', '', '419', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue F N°14 Les castors Familiaux Maraval Oran', '', '420', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'Sidi Hassan', '422', NULL, NULL, 'Cheraga', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Wilaya Tlemcen', '25 Rue Tindouf', '423', NULL, NULL, 'Ville Maghnia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Route d\'Ain Kihel', '424', NULL, NULL, 'Aïn Témouchent', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('lotissement urbain n 62', '', '425', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '2 Chemin Said Hamdine', '426', NULL, NULL, 'Bir Mourad Raïs', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '11 Rue Khaled Abdelkader', '427', NULL, NULL, 'Tlemcen 13000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('02 RUE LAMALI AHMED', '', '428', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Constantine', '', '429', NULL, NULL, '7 Tlili Said (r\'ssif)', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('24 Rue Docteur Saliège - El Biar- Alger.', '', '430', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Staoueli  Alger', '', '431', NULL, NULL, 'Rue des abattoirs', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger 16000.', '103 Boulevard Colonel Bougara', '432', NULL, NULL, 'El Biar', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger.', '', '434', NULL, NULL, 'Kouba. Apreval', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'P5PR+M9V', '436', NULL, NULL, 'Bab Ezzouar', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Boulevard Said Touati', '437', NULL, NULL, 'Bab El Oued 16000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Boussouf bt 17 n 10 Constantine', '', '438', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 594 logements cheraga', '', '439', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité khelil Dbk Tizi-Ouzou', '', '440', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cheraga', '', '441', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bir Mourad Raïs', '', '442', NULL, NULL, 'Avenue des Trois Frères Bouadou', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Chemin des Glycines', '443', NULL, NULL, 'Algiers', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cité zighoud youcef 2éme étage Chelghoum Laid MILA', '', '444', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Mahmoud bouhamidi Alger   ex joinville', '', '445', NULL, NULL, '6', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue d\'Evreux. Bejaia', '', '446', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('lotissement douzi 01 N 26 Bab Ezzouar Alger', '', '447', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('18 rue sebti oran 31000', '', '448', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'W44', '450', NULL, NULL, 'Oran', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Ali Abd Nour n-47  Skikda', '', '451', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('rue sidi-souffi Bejaia', '', '452', NULL, NULL, '12', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('21 Avenue Abdeslami Kouba', '', '453', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '454', NULL, NULL, 'Maghnia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'N82', '455', NULL, NULL, 'El Tarf', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Ptt 2 bp 310 ihedadden', '', '456', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '457', NULL, NULL, 'VMMM+48 Tlemcen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Sidi Moussa', '', '458', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cooperative Thafath Ain el hammam Tizi Ouzou', '', '459', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'GR4W+587', '461', NULL, NULL, 'Blida', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('UV 05 n°221 Ali Mendjeli Constantine', '', '462', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue de Fouka Kolea Tipaza  (devant le tribunale de Kolea)', '', '463', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 100 logements Bt F13 Chéraga', '', '464', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité Brakni Blida', '', '465', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue 5 Juillet Bordj Bou Arreridj', '', '466', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('04 rue de fouka commune kolea Tipaza- en face le tribunale de kolea-', '', '468', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('54.RUE SIDI HASSEN -CHERAGA-ALGER', '', '469', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('69 rue larbi ben mehidi oran', '', '470', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 400 logements bâtiment 57 n 2 birkhadem alger', '', '471', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'Palm Beach', '472', NULL, NULL, 'Staoueli', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Ali sadek Bordj El kiffan', '', '473', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('107 rue kara sliman kifen tlemcen', '', '474', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger said hamdine', '', '475', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Djelfa', '', '476', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Ahmed zaidat- imm Sadoudi- Azazga -  Tizi Ouzou', '', '477', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger.', '2', '478', NULL, NULL, 'Rue du 19 Mai 1956 Baba Hassen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Q32C+4PQ', '480', NULL, NULL, 'Béjaïa 06000', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', 'rue OUKIL EL HADJ', '483', NULL, NULL, 'El Mouradia. 16070', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cité 400 logements batiment 57 n 02 said hamdine', '', '484', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'G5WG+WVM', '485', NULL, NULL, 'Batna', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('avenue de 1er novembre Sidi Aich Wilaya de Bejaia', '', '486', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('ALGER', '', '487', NULL, NULL, '08 RUE CHERIF HAMANI', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'PC24+G2J', '488', NULL, NULL, 'Bir El Djir', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Plateux Oran', '', '490', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Hamaoui Hamid Elkseur', '', '491', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('H55G+F94 Batna Algerie', '', '492', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('cite de la paix tebessa', '', '493', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('706 coop cilfa bordj el kiffan Alger', '', '495', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bouira.', 'En face de la mosquée', '496', NULL, NULL, 'ECOTEC', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue ben choulak Mila', '', '497', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('3 Rue Cherchali Boualam Baba Hassen', '', '498', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('02 rue zibouch Mohamed Constantine rue petit', '', '499', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité bel-vue CRS Setif', '', '500', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Alger', '', '501', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('rue kabar adra centre cirta', '', '502', NULL, NULL, '6', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('w Tlemcen', '', '503', NULL, NULL, '125 cite Remchi', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('alger', '', '506', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Béjaïa', '', '507', NULL, NULL, 'Cité sidi ahmed rue Tikharoubine', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bejaïa', 'Promotion Sabrachou', '508', NULL, NULL, 'cartier sghir', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Q32F+RXF', '509', NULL, NULL, 'Béjaïa', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '5F8W+W3J', '510', NULL, NULL, 'Messâad', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cité 1er Novembre Batiment J n° 01 Koléa W.Tipasa', '', '511', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '5F8W+W3J', '512', NULL, NULL, 'Messâad', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'المصاعبة،، 9V75+QV6', '513', NULL, NULL, 'El Oued', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('31000 ORAN', '', '514', NULL, NULL, '1245 USTO HLM', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Souidanai', '515', NULL, NULL, 'Alger', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Saïd Hamdine bt 1.', '', '516', NULL, NULL, 'Route de Sidi Yahia', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('ZHUN SUD QUARTIER A TIZI-OUZOU', '', '518', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('22 rue colonel Mohamed chaabani Alger', '', '519', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'VMMH+96P', '520', NULL, NULL, 'Tlemcen', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Arezki Hamani', '', '521', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('53 avenue colonel Lotfi bab el oued alger', '', '522', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'Q885+VFH', '523', NULL, NULL, 'El Tarf', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '', '524', NULL, NULL, 'Rue belahouel belahouel  bâtiment Merouani matmar Mostaganem', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('31 rue mahmoud bouzebra skikda', '', '525', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Cheraga cité 100 logement bt c 1 numéro 4', '', '526', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue 1 novembre Rouiba - Alger', '', '528', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Bouzaréah Alger', 'Cité sahel', '531', NULL, NULL, 'villa 44', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', '07 cite repalle cap caxine', '532', NULL, NULL, 'El Hammamet 16085', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rue Président Ho Chi Minh - Oran', '', '533', NULL, NULL, '5', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('14 coop El yasmine - Bir El Djir - n° 10 - Oran', '', '534', NULL, NULL, '', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('', 'P5MM+JH9', '535', NULL, NULL, 'Bab Ezzouar', 'Algerie', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('alger', 'dz', '536', NULL, NULL, 'alger', '12 sdfdsf', '234525');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Kasilof', 'United States', '537', NULL, NULL, 'Alaska', '24486 Yukon Rd', '99610');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('setif', 'algerie', '538', NULL, NULL, 'setif', 'yahiaoui', '19000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Kasilof', 'United States', '539', NULL, NULL, 'Alaska', '24486 Yukon Rd', '99610');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('TiziOuzou', 'Algerie', '540', NULL, NULL, 'TiziOuzou', 'lotissement7', '15000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('TiziOuzou', 'Algérie', '541', NULL, NULL, 'TiziOuzou', 'lotissement7', '15000');
insert into `core_address` (`city`, `country`, `id`, `latitude`, `longitude`, `state`, `street`, `zip_code`) values ('Rouached', 'Algeria', '542', NULL, NULL, 'Mila', 'Rue Djouambi Mbarek', '43009');
